"""Pydantic schemas for IncidentLens telemetry ingestion."""

from __future__ import annotations

from datetime import UTC, datetime
from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field, field_validator


NonNegativeFloat = Annotated[float, Field(ge=0)]


class TelemetryEventCreate(BaseModel):
    """Incoming telemetry bucket generated by the simulator."""

    timestamp: datetime
    service: str
    latencies_ms: list[NonNegativeFloat] = Field(min_length=1)
    error_count: int = Field(ge=0)
    cpu_percent: float = Field(ge=0, le=100)
    memory_percent: float = Field(ge=0, le=100)

    @field_validator("timestamp")
    @classmethod
    def timestamp_must_include_timezone(cls, value: datetime) -> datetime:
        if value.tzinfo is None:
            raise ValueError("timestamp must include a timezone")
        return value.astimezone(UTC)

    @field_validator("service")
    @classmethod
    def service_must_not_be_blank(cls, value: str) -> str:
        normalized = value.strip()
        if not normalized:
            raise ValueError("service must not be blank")
        return normalized


class TelemetryEventRead(TelemetryEventCreate):
    """Telemetry bucket returned after it has been stored."""

    id: int

    model_config = ConfigDict(from_attributes=True)


class EventIngestResponse(BaseModel):
    """Response returned after a telemetry bucket is accepted."""

    status: str
    event: TelemetryEventRead


class HealthResponse(BaseModel):
    status: str
